export const mockWallets = [
  {
    id: "W-001",
    name: "Rajesh Kumar",
    initials: "RK",
    avatarColor: "bg-blue-100 text-blue-700",
    balance: 7682,
    reserved: 1500,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Gold",
    state: "Maharashtra",
    city: "Mumbai",
    date: "2026-05-10",
  },
  {
    id: "W-002",
    name: "Priya Autos",
    initials: "PA",
    avatarColor: "bg-indigo-100 text-indigo-700",
    balance: 42,
    reserved: 0,
    status: "Critical",
    statusStyle: "bg-red-50 text-red-600",
    balanceColor: "text-red-500",
    tier: "Bronze",
    state: "Karnataka",
    city: "Bangalore",
    date: "2026-05-22",
  },
  {
    id: "W-003",
    name: "Suresh K.",
    initials: "SK",
    avatarColor: "bg-amber-100 text-amber-700",
    balance: 3200,
    reserved: 900,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Silver",
    state: "Delhi",
    city: "New Delhi",
    date: "2026-06-01",
  },
  {
    id: "W-004",
    name: "Ravi Mehta",
    initials: "RM",
    avatarColor: "bg-red-100 text-red-700",
    balance: 580,
    reserved: 800,
    status: "Low",
    statusStyle: "bg-amber-50 text-amber-700",
    balanceColor: "text-amber-600",
    tier: "Bronze",
    state: "Maharashtra",
    city: "Pune",
    date: "2026-05-28",
  },
  {
    id: "W-005",
    name: "Ananya Sharma",
    initials: "AS",
    avatarColor: "bg-pink-100 text-pink-700",
    balance: 12500,
    reserved: 3000,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Platinum",
    state: "Tamil Nadu",
    city: "Chennai",
    date: "2026-04-15",
  },
  {
    id: "W-006",
    name: "Amit Patel",
    initials: "AP",
    avatarColor: "bg-teal-100 text-teal-700",
    balance: 2100,
    reserved: 400,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Silver",
    state: "Gujarat",
    city: "Ahmedabad",
    date: "2026-05-02",
  },
  {
    id: "W-007",
    name: "Vikram Singh",
    initials: "VS",
    avatarColor: "bg-purple-100 text-purple-700",
    balance: 850,
    reserved: 1000,
    status: "Low",
    statusStyle: "bg-amber-50 text-amber-700",
    balanceColor: "text-amber-600",
    tier: "Bronze",
    state: "Rajasthan",
    city: "Jaipur",
    date: "2026-05-18",
  },
  {
    id: "W-008",
    name: "Karan Johar",
    initials: "KJ",
    avatarColor: "bg-rose-100 text-rose-700",
    balance: 15400,
    reserved: 2500,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Platinum",
    state: "Maharashtra",
    city: "Mumbai",
    date: "2026-06-03",
  },
  {
    id: "W-009",
    name: "Sneha Reddy",
    initials: "SR",
    avatarColor: "bg-emerald-100 text-emerald-700",
    balance: 4800,
    reserved: 1200,
    status: "Healthy",
    statusStyle: "bg-emerald-50 text-emerald-700",
    tier: "Gold",
    state: "Telangana",
    city: "Hyderabad",
    date: "2026-05-30",
  }
];

export const mockTransactions = [
  {
    id: "TXN-8821",
    consultantId: "W-001",
    type: "topup",
    name: "Rajesh Kumar — top-up",
    sub: "Wallet credited manually · Ref #TXN-8821",
    amount: 5000,
    time: "10 min ago",
    date: "2026-06-05",
  },
  {
    id: "TXN-8820",
    consultantId: "W-002",
    type: "ppc_cpi",
    name: "Priya Autos — CPI charge",
    sub: "Inquiry on Mercedes C200 · Ad #AD-0391",
    amount: -35,
    time: "22 min ago",
    date: "2026-06-05",
  },
  {
    id: "TXN-8819",
    consultantId: "W-001",
    type: "ppc_cpc",
    name: "Rajesh Kumar — CPC charge",
    sub: "6 clicks · BMW X1 homepage · Ad #AD-0482",
    amount: -27,
    time: "35 min ago",
    date: "2026-06-05",
  },
  {
    id: "TXN-8804",
    consultantId: "W-004",
    type: "refund",
    name: "Ravi Mehta — refund issued",
    sub: "Campaign disabled by admin · ₹90 returned",
    amount: 90,
    time: "2 days ago",
    date: "2026-06-03",
  },
  {
    id: "TXN-8800",
    consultantId: "W-003",
    type: "topup",
    name: "Suresh K. — top-up",
    sub: "Wallet credited · Ref #TXN-8800",
    amount: 2000,
    time: "3 days ago",
    date: "2026-06-02",
  },
  {
    id: "TXN-8795",
    consultantId: "W-004",
    type: "ppc_cpc",
    name: "Ravi Mehta — CPC charge",
    sub: "14 clicks · Fortuner homepage · Ad #AD-0483",
    amount: -42,
    time: "3 days ago",
    date: "2026-06-02",
  },
  {
    id: "TXN-8790",
    consultantId: "W-005",
    type: "inspection",
    name: "Ananya Sharma — Inspection fee",
    sub: "Standard inspection · Audi A4 · Ad #AD-0210",
    amount: -1500,
    time: "4 days ago",
    date: "2026-06-01",
  },
  {
    id: "TXN-8788",
    consultantId: "W-006",
    type: "topup",
    name: "Amit Patel — top-up",
    sub: "Wallet credited · Ref #TXN-8788",
    amount: 1500,
    time: "5 days ago",
    date: "2026-05-31",
  },
  {
    id: "TXN-8785",
    consultantId: "W-006",
    type: "ppc_cpi",
    name: "Amit Patel — CPI charge",
    sub: "Inquiry on Creta · Ad #AD-0302",
    amount: -40,
    time: "5 days ago",
    date: "2026-05-31",
  },
  {
    id: "TXN-8780",
    consultantId: "W-007",
    type: "inspection",
    name: "Vikram Singh — Inspection fee",
    sub: "Detailed report · Scorpio Classic · Ad #AD-0567",
    amount: -1800,
    time: "6 days ago",
    date: "2026-05-30",
  },
  {
    id: "TXN-8775",
    consultantId: "W-008",
    type: "topup",
    name: "Karan Johar — top-up",
    sub: "Wallet credited · Ref #TXN-8775",
    amount: 10000,
    time: "1 week ago",
    date: "2026-05-28",
  },
  {
    id: "TXN-8770",
    consultantId: "W-009",
    type: "refund",
    name: "Sneha Reddy — refund issued",
    sub: "Ad moderation fee adjustment",
    amount: 250,
    time: "1 week ago",
    date: "2026-05-28",
  },
  {
    id: "TXN-8765",
    consultantId: "W-008",
    type: "ppc_cpc",
    name: "Karan Johar — CPC charge",
    sub: "45 clicks · Thar profile feature",
    amount: -135,
    time: "1 week ago",
    date: "2026-05-28",
  },
  {
    id: "TXN-8760",
    consultantId: "W-001",
    type: "inspection",
    name: "Rajesh Kumar — Inspection fee",
    sub: "Inspector visit · Civic hybrid",
    amount: -1200,
    time: "2 weeks ago",
    date: "2026-05-22",
  }
];
