export const DUMMY_PENDING_APPROVALS = [
  {
    id: "VH-845701",
    title: "Hyundai Creta • SX • 2022",
    consultant: "Prime Wheels",
    city: "Ahmedabad",
    tier: "Premium",
    submissionType: "New",
    inspection: "AVX_INSPECTED",
    risk: "Low",
    submittedAtHours: 1.5,
    slaHours: 6,
    registrationNo: "GJ01AB4521",
    boostActive: true,
    previousStatus: "Draft",
    thumb:
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1200&auto=format&fit=crop",
    priceOld: null,
    priceNew: 1180000,
    fuelOld: null,
    fuelNew: "Petrol",
    descOld: null,
    descNew: "Single owner, clean condition, premium maintained car.",
    photoOldCount: null,
    photoNewCount: 10,
    duplicateFound: false,
    duplicateVehicleId: null,
    marketAvg: 1215000,
    priceDeviation: -3,
    mediaFlags: ["No major issues"],
    claimsFlags: ["Single owner"],
    inspectionValid: true,
  },
  {
    id: "VH-845702",
    title: "Maruti Baleno • Alpha • 2021",
    consultant: "Auto Hub",
    city: "Surat",
    tier: "Basic",
    submissionType: "Edited",
    inspection: "SELF_INSPECTED",
    risk: "Moderate",
    submittedAtHours: 4.2,
    slaHours: 6,
    registrationNo: "GJ05MN8821",
    boostActive: false,
    previousStatus: "Active",
    thumb:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop",
    priceOld: 680000,
    priceNew: 590000,
    fuelOld: "Petrol",
    fuelNew: "Petrol",
    descOld: "Well maintained hatchback",
    descNew: "Well maintained hatchback, accident free, best in class mileage",
    photoOldCount: 8,
    photoNewCount: 12,
    duplicateFound: false,
    duplicateVehicleId: null,
    marketAvg: 655000,
    priceDeviation: -10,
    mediaFlags: ["2 new photos added"],
    claimsFlags: ["Accident free"],
    inspectionValid: true,
  },
  {
    id: "VH-845703",
    title: "Honda City • VX CVT • 2020",
    consultant: "Metro Cars",
    city: "Vadodara",
    tier: "Pro",
    submissionType: "Reactivation",
    inspection: "AI_INSPECTED",
    risk: "High",
    submittedAtHours: 7.8,
    slaHours: 6,
    registrationNo: "GJ06RT9981",
    boostActive: false,
    previousStatus: "Inactive",
    thumb:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop",
    priceOld: 950000,
    priceNew: 735000,
    fuelOld: "Petrol",
    fuelNew: "Diesel",
    descOld: "Top model sedan",
    descNew: "Accident free, 100% engine guarantee, premium family sedan",
    photoOldCount: 7,
    photoNewCount: 11,
    duplicateFound: true,
    duplicateVehicleId: "VH-844990",
    marketAvg: 990000,
    priceDeviation: -26,
    mediaFlags: ["WhatsApp number visible", "External watermark detected"],
    claimsFlags: ["100% engine guarantee", "Accident free"],
    inspectionValid: true,
  },
  {
    id: "VH-845704",
    title: "Tata Nexon • XZ+ • 2023",
    consultant: "Premium Drive",
    city: "Ahmedabad",
    tier: "Premium",
    submissionType: "Edited",
    inspection: "AVX_INSPECTED",
    risk: "Low",
    submittedAtHours: 2.4,
    slaHours: 6,
    registrationNo: "GJ01NX1254",
    boostActive: true,
    previousStatus: "Active",
    thumb:
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=1200&auto=format&fit=crop",
    priceOld: 1375000,
    priceNew: 1360000,
    fuelOld: "Petrol",
    fuelNew: "Petrol",
    descOld: "Top model compact SUV",
    descNew: "Top model compact SUV, company maintained, no issues",
    photoOldCount: 9,
    photoNewCount: 10,
    duplicateFound: false,
    duplicateVehicleId: null,
    marketAvg: 1385000,
    priceDeviation: -2,
    mediaFlags: ["No major issues"],
    claimsFlags: ["No issues"],
    inspectionValid: true,
  },
];