export const DUMMY_FLAGGED_LISTINGS = [
  {
    id: "VH-78231",
    thumb:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=60",
    title: "Hyundai Creta SX • 2021",
    consultant: "Metro Auto Hub",
    tier: "Premium",
    city: "Ahmedabad",
    risk: "High",
    flagSource: "System",
    flagCategory: "Duplicate Registration",
    flagReason: "Same registration detected across multiple active listings.",
    inquiries: 24,
    status: "Investigating",
    daysOpen: 4,
    disputeLinked: true,
    dateFlagged: "2026-02-12",
    inspectionStatus: "AVX_INSPECTED",
    boostActive: true,
    totalComplaints: 3,
    buyerId: "#4821",
    comment: "Vehicle shows accident damage not mentioned.",
    autoFlag: "Duplicate Registration",
    detectedListing: "#7342",
    price: "₹11,80,000",
    description:
      "Single owner, clean interior, insured, recently serviced. Suspicious mismatch found in uploaded registration.",
    specs: ["Diesel", "Automatic", "56,000 km", "Top Variant"],
    priceDeviation: "-34%",
    duplicateDetected: "YES",
    ipAnomaly: "YES",
    inspectionValid: "YES",
    complaintCount: 3,
    chatFlags: "Phone number sharing, external deal attempt",
    consultantHistory: {
      totalDisputes: 5,
      previousFlags: 3,
      rankingPenalties: 2,
      tamperingHistory: "No",
    },
  },
  {
    id: "VH-78232",
    thumb:
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&auto=format&fit=crop&q=60",
    title: "Maruti Baleno Alpha • 2020",
    consultant: "Cityline Wheels",
    tier: "Pro",
    city: "Surat",
    risk: "Moderate",
    flagSource: "Buyer",
    flagCategory: "Misleading Description",
    flagReason: "Buyer claims accidental history was not disclosed.",
    inquiries: 16,
    status: "Under Review",
    daysOpen: 2,
    disputeLinked: true,
    dateFlagged: "2026-02-14",
    inspectionStatus: "AI_INSPECTED",
    boostActive: false,
    totalComplaints: 1,
    buyerId: "#4152",
    comment: "Vehicle bonnet and bumper seem repainted.",
    autoFlag: "-",
    detectedListing: "-",
    price: "₹6,40,000",
    description:
      "Petrol automatic hatchback with premium interiors and alloy wheels.",
    specs: ["Petrol", "Automatic", "41,000 km", "Top Model"],
    priceDeviation: "-12%",
    duplicateDetected: "NO",
    ipAnomaly: "NO",
    inspectionValid: "YES",
    complaintCount: 1,
    chatFlags: "Minor complaint language",
    consultantHistory: {
      totalDisputes: 2,
      previousFlags: 1,
      rankingPenalties: 0,
      tamperingHistory: "No",
    },
  },
  {
    id: "VH-78233",
    thumb:
      "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=600&auto=format&fit=crop&q=60",
    title: "Mahindra Thar LX • 2022",
    consultant: "Prime Cars Studio",
    tier: "Premium",
    city: "Rajkot",
    risk: "High",
    flagSource: "Inspection",
    flagCategory: "Fake Inspection Upload",
    flagReason: "Inspection images do not match vehicle chassis and angle history.",
    inquiries: 11,
    status: "Escalated",
    daysOpen: 6,
    disputeLinked: false,
    dateFlagged: "2026-02-10",
    inspectionStatus: "SELF_INSPECTED",
    boostActive: true,
    totalComplaints: 2,
    buyerId: "-",
    comment: "-",
    autoFlag: "Inspection Inconsistency",
    detectedListing: "-",
    price: "₹15,90,000",
    description:
      "Off-road ready Thar with custom alloys and leather seats.",
    specs: ["Diesel", "Manual", "18,000 km", "4x4"],
    priceDeviation: "-6%",
    duplicateDetected: "NO",
    ipAnomaly: "YES",
    inspectionValid: "NO",
    complaintCount: 2,
    chatFlags: "Consultant pushed for direct payment",
    consultantHistory: {
      totalDisputes: 4,
      previousFlags: 4,
      rankingPenalties: 3,
      tamperingHistory: "Yes",
    },
  },
  {
    id: "VH-78234",
    thumb:
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&auto=format&fit=crop&q=60",
    title: "Honda City VX • 2019",
    consultant: "Nexa Point Motors",
    tier: "Basic",
    city: "Vadodara",
    risk: "Low",
    flagSource: "Buyer",
    flagCategory: "Minor Data Mismatch",
    flagReason: "Fuel type mismatch in one uploaded document.",
    inquiries: 9,
    status: "Resolved",
    daysOpen: 1,
    disputeLinked: false,
    dateFlagged: "2026-02-15",
    inspectionStatus: "AVX_INSPECTED",
    boostActive: false,
    totalComplaints: 1,
    buyerId: "#4012",
    comment: "RC image and listing field mismatch.",
    autoFlag: "-",
    detectedListing: "-",
    price: "₹8,25,000",
    description: "Comfort sedan with clean cabin and documented service history.",
    specs: ["Petrol", "Manual", "52,000 km", "VX"],
    priceDeviation: "-4%",
    duplicateDetected: "NO",
    ipAnomaly: "NO",
    inspectionValid: "YES",
    complaintCount: 1,
    chatFlags: "None",
    consultantHistory: {
      totalDisputes: 1,
      previousFlags: 0,
      rankingPenalties: 0,
      tamperingHistory: "No",
    },
  },
  {
    id: "VH-78235",
    thumb:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=60",
    title: "Kia Seltos GTX+ • 2023",
    consultant: "Elite Drive House",
    tier: "Premium",
    city: "Ahmedabad",
    risk: "Moderate",
    flagSource: "System",
    flagCategory: "Price Anomaly Detection",
    flagReason: "Vehicle listed 31% below market average for same model & year.",
    inquiries: 27,
    status: "Under Review",
    daysOpen: 3,
    disputeLinked: false,
    dateFlagged: "2026-02-13",
    inspectionStatus: "AI_INSPECTED",
    boostActive: true,
    totalComplaints: 0,
    buyerId: "-",
    comment: "-",
    autoFlag: "Price Anomaly",
    detectedListing: "-",
    price: "₹10,20,000",
    description: "Feature-rich SUV with panoramic roof and ADAS support.",
    specs: ["Petrol", "Automatic", "12,000 km", "GTX+"],
    priceDeviation: "-31%",
    duplicateDetected: "NO",
    ipAnomaly: "NO",
    inspectionValid: "YES",
    complaintCount: 0,
    chatFlags: "None",
    consultantHistory: {
      totalDisputes: 2,
      previousFlags: 1,
      rankingPenalties: 1,
      tamperingHistory: "No",
    },
  },
];